#### Preamble ####
# Purpose: Tests the structure and validity of the simulated datasets
# Author: Jiwon Choi
# Date: 26 November 2024
# Contact: jwon.choi@mail.utoronto.ca
# License: MIT
# Pre-requisites: 
# - The `tidyverse` package must be installed and loaded
# - The datasets generated by the simulation script must exist

#### Workspace setup ####
library(tidyverse)

# Load the datasets
age_data <- read_csv("data/00-simulated_data/simulated_age_data.csv")
dwelling_data <- read_csv("data/00-simulated_data/simulated_dwelling_data.csv")
household_data <- read_csv("data/00-simulated_data/simulated_household_data.csv")

#### Test Age Dataset ####

message("Testing Age Dataset...")
# Test if the dataset was successfully loaded
if (exists("age_data")) {
  message("Test Passed: Age dataset loaded successfully.")
} else {
  stop("Test Failed: Age dataset could not be loaded.")
}

# Check if the dataset has the correct number of rows
expected_age_rows <- 19  # 19 age groups
if (nrow(age_data) == expected_age_rows) {
  message("Test Passed: Age dataset has the correct number of rows.")
} else {
  stop("Test Failed: Age dataset does not have the correct number of rows.")
}

# Check if the dataset has the correct number of columns
expected_wards <- 25  # Wards 1 to 25
if (ncol(age_data) == (expected_wards + 2)) {  # +2 for 'City of Toronto Profiles' and 'Toronto'
  message("Test Passed: Age dataset has the correct number of columns.")
} else {
  stop("Test Failed: Age dataset does not have the correct number of columns.")
}

#### Test Dwelling Type Dataset ####

message("Testing Dwelling Type Dataset...")
# Test if the dataset was successfully loaded
if (exists("dwelling_data")) {
  message("Test Passed: Dwelling dataset loaded successfully.")
} else {
  stop("Test Failed: Dwelling dataset could not be loaded.")
}

# Check if the dataset has the correct number of rows
expected_dwelling_rows <- 8  # 8 dwelling types
if (nrow(dwelling_data) == expected_dwelling_rows) {
  message("Test Passed: Dwelling dataset has the correct number of rows.")
} else {
  stop("Test Failed: Dwelling dataset does not have the correct number of rows.")
}

# Check if the dataset has the correct number of columns
if (ncol(dwelling_data) == (expected_wards + 2)) {  # +2 for 'City of Toronto Profiles' and 'Toronto'
  message("Test Passed: Dwelling dataset has the correct number of columns.")
} else {
  stop("Test Failed: Dwelling dataset does not have the correct number of columns.")
}

#### Test Household Size Dataset ####

message("Testing Household Size Dataset...")
# Test if the dataset was successfully loaded
if (exists("household_data")) {
  message("Test Passed: Household dataset loaded successfully.")
} else {
  stop("Test Failed: Household dataset could not be loaded.")
}

# Check if the dataset has the correct number of rows
expected_household_rows <- 6  # 6 household sizes
if (nrow(household_data) == expected_household_rows) {
  message("Test Passed: Household dataset has the correct number of rows.")
} else {
  stop("Test Failed: Household dataset does not have the correct number of rows.")
}

# Check if the dataset has the correct number of columns
if (ncol(household_data) == (expected_wards + 2)) {  # +2 for 'City of Toronto Profiles' and 'Toronto'
  message("Test Passed: Household dataset has the correct number of columns.")
} else {
  stop("Test Failed: Household dataset does not have the correct number of columns.")
}

#### General Validity Tests ####

# Check for missing values in all datasets
datasets <- list(age_data = age_data, dwelling_data = dwelling_data, household_data = household_data)

for (name in names(datasets)) {
  data <- datasets[[name]]
  if (all(!is.na(data))) {
    message(paste("Test Passed:", name, "dataset contains no missing values."))
  } else {
    stop(paste("Test Failed:", name, "dataset contains missing values."))
  }
}

message("All tests completed.")
